
package com.yilv.webservice.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SendMessageServiceImplService", targetNamespace = "http://impl.webservice.yilv.com/", wsdlLocation = "http://localhost:8080/yi_xmpp/services/SendMessageService?wsdl")
public class SendMessageServiceImplService
    extends Service
{

    private final static URL SENDMESSAGESERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException SENDMESSAGESERVICEIMPLSERVICE_EXCEPTION;
    private final static QName SENDMESSAGESERVICEIMPLSERVICE_QNAME = new QName("http://impl.webservice.yilv.com/", "SendMessageServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/yi_xmpp/services/SendMessageService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SENDMESSAGESERVICEIMPLSERVICE_WSDL_LOCATION = url;
        SENDMESSAGESERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public SendMessageServiceImplService() {
        super(__getWsdlLocation(), SENDMESSAGESERVICEIMPLSERVICE_QNAME);
    }

    public SendMessageServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SENDMESSAGESERVICEIMPLSERVICE_QNAME, features);
    }

    public SendMessageServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SENDMESSAGESERVICEIMPLSERVICE_QNAME);
    }

    public SendMessageServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SENDMESSAGESERVICEIMPLSERVICE_QNAME, features);
    }

    public SendMessageServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SendMessageServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SendMessageService
     */
    @WebEndpoint(name = "SendMessageServiceImplPort")
    public SendMessageService getSendMessageServiceImplPort() {
        return super.getPort(new QName("http://impl.webservice.yilv.com/", "SendMessageServiceImplPort"), SendMessageService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SendMessageService
     */
    @WebEndpoint(name = "SendMessageServiceImplPort")
    public SendMessageService getSendMessageServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.webservice.yilv.com/", "SendMessageServiceImplPort"), SendMessageService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SENDMESSAGESERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw SENDMESSAGESERVICEIMPLSERVICE_EXCEPTION;
        }
        return SENDMESSAGESERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
