package com.yilv.webservice.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.4-b01 Generated
 * source version: 2.2
 * 
 */
@WebService(name = "SendMessageService", targetNamespace = "http://webservice.yilv.com/")
@XmlSeeAlso({ ObjectFactory.class })
public interface SendMessageService {

	/**
	 * 
	 * @param message
	 * @return returns com.yilv.webservice.client.Result
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "sendMessage", targetNamespace = "http://webservice.yilv.com/", className = "com.yilv.webservice.client.SendMessage")
	@ResponseWrapper(localName = "sendMessageResponse", targetNamespace = "http://webservice.yilv.com/", className = "com.yilv.webservice.client.SendMessageResponse")
	public Result sendMessage(@WebParam(name = "message", targetNamespace = "") String message);

}
